# Generated by Django 4.2.21 on 2025-05-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_typingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typing_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
