# Generated by Django 4.2.9 on 2025-05-23 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': '배우',
                'verbose_name_plural': '배우 목록',
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '장르',
                'verbose_name_plural': '장르 목록',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('vote_average', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(default=0, help_text='분 단위 상영 시간')),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': '영화',
                'verbose_name_plural': '영화 목록',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieLikeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '영화 좋아요',
                'verbose_name_plural': '영화 좋아요 목록',
                'db_table': 'movie_like_users',
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'verbose_name': '영화-장르 연결',
                'verbose_name_plural': '영화-장르 연결 목록',
                'db_table': 'movie_genre',
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'verbose_name': '영화-배우 연결',
                'verbose_name_plural': '영화-배우 연결 목록',
                'db_table': 'movie_actor',
                'unique_together': {('movie', 'actor')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieActor', to='movies.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieGenre', to='movies.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_movies', through='movies.MovieLikeUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
